### ISSUE TITLE
Use of fstrings to clean up the printing of the heart with lines

### ISSUE THREAD

**Issue by rajpatel0** [ZenithDS/lovesay#1]
Using python's f strings will make your life easier, and paired with some prechecking can clean up much of the try-excepts that you use currently. 
https://realpython.com/python-f-strings/

**Comment by ZenithDS** [comment]
Thank you for the suggestion Raj!! as per your advice, I cleaned up the script with some prechecking and f strings. I've pushed out the changes as well, let me know what you think!

**Comment by rajpatel0** [comment]
Looks good.
