### ISSUE TITLE
Binary location

### ISSUE THREAD

**Issue by Literal-Eval** [ZenithDS/lovesay#4]
Hello mate. Found your project cute and wanted to install it. For the pip part, pip or pip3 simply say that there is no package with this name. So I tried installing with the second method, i.e., Poetry. So I installed Poetry and installed the project with it as mentioned. But still lovesay isn't a recognized command in the system and also I can't find where exactly poetry installed it.

So what I want to know is, how to run this program ?

**Comment by ZenithDS** [comment]
Hi! lovesay is up on PyPI you should be able to install it from there. In any case, I've updated the instructions to install it from source, please let me know if that works :)

**Comment by Literal-Eval** [comment]
Works. Thanks :)
